### ISSUE TITLE
Unrecognized keyword ON, DUPLICATE and KEY

### ISSUE THREAD

**Issue by ThaFlaxx** [phpmyadmin/sql-parser#50] opened 2016-05-22 14:44 UTC
### Steps to reproduce
```
INSERT INTO `champs` (`id`,`key`) VALUES (412,'Thresh')
ON DUPLICATE KEY UPDATE id=412,key='Thresh'
```

### Actual behaviour
```
#1: Unrecognized keyword. (near "ON" at position xx)
#2: Unrecognized keyword. (near "DUPLICATE" at position xx)
#3: Unrecognized keyword. (near "KEY" at position xx)
```

### Server configuration
**Web server:**
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.21

**Database:**
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $

**phpMyAdmin version:**
4.6.1

## Same Issue?
[Unrecognized keyword FULL and OUTER #12205](https://github.com/phpmyadmin/phpmyadmin/issues/12205)

I am not sure if the SQL Command are 100% right, but i hope so.
Would be nice if someone could confirm this bug.

**Comment by devenbansod** [comment] 2016-09-03 07:02
Related to/possible duplicate of #11628

**Closed** 2016-09-13 08:34 UTC
Labels: bug
