### ISSUE TITLE
Syntax error with row_number alias

### ISSUE THREAD

**Issue by DorianCoding** [phpmyadmin/sql-parser#387] opened 2022-11-20 10:27 UTC
When using ROW_NUMBER and an alias such as :

```sql
SELECT ROW_NUMBER() OVER (ORDER BY `start`)
```

Phpmyadmin is showing an error but the query works.

It says "An alias was previously found" near the index.

![image](https://user-images.githubusercontent.com/108593662/202897054-6958b4a2-f64b-43ed-9173-5a51976b150e.png)

### Server configuration

- Operating system: Ubuntu
- Web server: Nginx + Apache
- Database version:  10.6.7-MariaDB-2ubuntu1.1 - Ubuntu 22.04
- PHP version: 8.1.2-1ubuntu2.8
- phpMyAdmin version:  5.1.1deb5ubuntu1

### Client configuration

- Browser: Firefox 107.0
- Operating system: Windows 10 64 bits

**Comment by williamdes** [comment] 2022-11-20 12:57
Bonjour !
Thank you for reporting this issue, I moved it here so we can investigate about it.
@iifawzi I am not sure if any of your recent PRs fix this one ?

**Comment by iifawzi** [comment] 2022-11-21 10:41
I bet that we've seen this bug before, I will take a deeper look

**Comment by iifawzi** [comment] 2022-11-21 11:07
The issue is already fixed by https://github.com/phpmyadmin/sql-parser/pull/360#issuecomment-954721943.
Kindly @DorianCoding, can you test with the latest version? (5.2.0)

**Comment by williamdes** [comment] 2022-11-21 12:10
__[(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)_

**Comment by DorianCoding** [comment] 2022-11-21 16:48
> The issue is already fixed by [#360 (comment)](https://github.com/phpmyadmin/sql-parser/pull/360#issuecomment-954721943). Kindly @DorianCoding, can you test with the latest version? (5.2.0)

It seems indeed that the problem is solved using phpmyadmin 5.2 with XAMPP on Windows (with same browser). I guess I just have to wait the update of ubuntu packages then.

**Comment by williamdes** [comment] 2022-11-21 17:26
> > The issue is already fixed by [#360 (comment)](https://github.com/phpmyadmin/sql-parser/pull/360#issuecomment-954721943). Kindly @DorianCoding, can you test with the latest version? (5.2.0)
> 
> It seems indeed that the problem is solved using phpmyadmin 5.2 with XAMPP on Windows (with same browser). I guess I just have to wait the update of ubuntu packages then.

I am the one responsible for the packaging on Ubuntu and Debian, I am quite behind schedule and sorry about that. I will keep you updated

**Comment by williamdes** [comment] 2023-04-21 19:17
> I am the one responsible for the packaging on Ubuntu and Debian, I am quite behind schedule and sorry about that. I will keep you updated

It's been a while, the PPA is updated for Jammy. Can you please check our [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by williamdes** [comment] 2024-04-20 23:13
Thank you for confirming this

**Comment by niconoe-** [comment] 2024-09-20 08:24
I can't reproduce the error using the parser on 5.10.x.

This might be fixed by the fact `ROW_NUMBER` is now included in the dictionnaries of functions, which wasn't the case before #572.

@williamdes I let you give it a try to double-check and confirm this is fixed now.

**Comment by williamdes** [comment] 2024-12-21 13:26
Indeed, I can not see a syntax error anymore.
Thank you for all the work done !

**Closed by williamdes** 2024-12-21 13:26 UTC
Labels: bug
