### ISSUE TITLE
INSERT .. (SELECT ...) fails due to parenthesis

### ISSUE THREAD

**Issue by Unisolve** [phpmyadmin/sql-parser#163] opened 2017-08-10 11:16 UTC
In the php-sqllint tool, this sample MySQL statement is flagged as a syntax error:

INSERT IGNORE INTO user_role (member_id, role_id) (SELECT id, '4150C5' FROM mem WHERE mem_type='Full' AND email NOT LIKE '%example.com');

If I remove the parenthesis, it's no longer considered an error, ie:

INSERT IGNORE INTO user_role (member_id, role_id) SELECT id, '4150C5' FROM mem WHERE mem_type='Full' AND email NOT LIKE '%example.com';

I haven't tested this directly in phpmyadmin, but I believe it's the phpmyadmin sql-parser that is raising the error, not php-sqllint.
 
Cheers,

Simon

**Comment by nijel** [comment] 2017-08-10 13:10
Duplicate of #159 

Thanks for your report, but this is caused by same thing as #159.

**Closed by nijel** 2017-08-10 13:10 UTC
